### PR TITLE
fix type assert faults

### LINKED ISSUE #1954: Nightly K8s Matrix CI 2023-06-28: Failed
action url: https://github.com/spidernet-io/spiderpool/actions/runs/5405448105

### PR DESCRIPTION
**Pull request by Icarus9913**
Signed-off-by: Icarus9913 [icaruswu66@qq.com](mailto:icaruswu66@qq.com)

**What this PR does / why we need it**:
fix bug

**Which issue(s) this PR fixes**:
close #1954, #1962

### CODE REVIEW

**Review by weizhoublue — APPROVED** [review]

**Review by cyclinder — DISMISSED** [review]

File: cmd/coordinator/cmd/command_del.go [hunk 1]
```diff
@@ -89,9 +89,10 @@ func CmdDel(args *skel.CmdArgs) (err error) {
...
 		vethLink, err := netlink.LinkByName(hostVeth)
 		if err != nil {
-			if _, ok := err.(*netlink.LinkNotFoundError); ok {
+			if _, ok := err.(netlink.LinkNotFoundError); ok {
 				logger.Debug("Host veth has gone, nothing to do", zap.String("HostVeth", hostVeth))
 			} else {
+				logger.Sugar().Errorf("failed to get host veth device %s: %v", hostVeth, err)
 				return fmt.Errorf("failed to get host veth device %s: %w", hostVeth, err)
 			}
 		}
```
Comment (cyclinder) [inline cmd/coordinator/cmd/command_del.go:98]:
```suggestion
		if err != nil {
			if _, ok := err.(netlink.LinkNotFoundError); ok {
				logger.Debug("Host veth has gone, nothing to do", zap.String("HostVeth", hostVeth))
			} else {
				logger.Sugar().Errorf("failed to get host veth device %s: %v", hostVeth, err)
				return fmt.Errorf("failed to get host veth device %s: %w", hostVeth, err)
			}
		}else {
		      if err = netlink.LinkDel(vethLink); err != nil {
			      logger.Error("failed to del hostVeth", zap.Error(err))
			      return fmt.Errorf("failed to del hostVeth %s: %w", hostVeth, err)
		      } else {
			      logger.Error("success to del hostVeth", zap.String("HostVeth", hostVeth))
		      }
	}
```

Comment (cyclinder) [reply cmd/coordinator/cmd/command_del.go:98]:
```go
		vethLink, err := netlink.LinkByName(hostVeth)
		if err != nil {
			if _, ok := err.(netlink.LinkNotFoundError); ok {
				logger.Debug("Host veth has gone, nothing to do", zap.String("HostVeth", hostVeth))
			} else {
				return fmt.Errorf("failed to get host veth device %s: %w", hostVeth, err)
			}
		} else {
			if err = netlink.LinkDel(vethLink); err != nil {
				logger.Error("failed to del hostVeth", zap.Error(err))
				return fmt.Errorf("failed to del hostVeth %s: %w", hostVeth, err)
			} else {
				logger.Error("success to del hostVeth", zap.String("HostVeth", hostVeth))
			}
		}
```

**Review by cyclinder — APPROVED** [review]

**Review by cyclinder — APPROVED** [review]
