### PR TITLE
fix ipam block with ip address used out

### LINKED ISSUE #2517: IPAM allocation blocked
**Describe the version**
version about:
1. spiderpool: `v0.8.0-rc1`

**Describe the bug**
1:1 allocation case for performance test.

1 IPPool with 1000 IP addresses and create 1 deployment with 1000 replicas. At the end, the IPAM blocked and one Pod can't start correctly with no IP address. But you can notice the IPPool resource already record the pod and allocated its IP. What's more, the pod corresponding SpiderEndpoint not exist.

With the upper description, I image the possibility to reproduce it:
step 1: In the allocation steps, the IPPool allocate IPs correctly.
step 2: Failed to create a SpiderEndpoint object, the spiderpool-agent record this allocation IPs in the memory db.
step3: The spiderpool-agent restart
step4: In the  reallocation, the spiderpool-agent component try to find the previous allocation details in the memory db but find nothing.
step5: The spiderpool-agent component try to allocate a new IP address but found the whole IPPool IPs were allocated.

Notice: For spiderpool-controller GC system, the pod is still exist but can't find the SpiderEndpoint resource. So, the GC scanAll will skip to release the previous allocated IPs.

### PR DESCRIPTION
**Pull request by Icarus9913**
As issue #2517 described, we need try to circulate traversal the whole IPPool allocated IPs to find the previous allocated IP address once the whole IPPool IP addresses used out.

It might reduce performance, but this is the simplest and cause less impaction to solve this problem.

And we only do this when we meet IP addresses used out case. In other case, the spiderpool-agent component still find new free IP address to allocate for the pod and the spiderpool-controller component will use GC scanAll to release the previous IP addresses.

Signed-off-by: Icarus9913 [icaruswu66@qq.com](mailto:icaruswu66@qq.com)

**What this PR does / why we need it**:
fix bug

**Which issue(s) this PR fixes**:
close #2517

### CODE REVIEW

File: pkg/ippoolmanager/ippool_manager.go [hunk 1]
```diff
@@ -166,22 +178,19 @@ func (im *ipPoolManager) genRandomIP(ctx context.Context, nic string, ipPool *sp
...
-	var tmpPod *corev1.Pod
-	if im.config.EnableKubevirtStaticIP && podController.APIVersion == kubevirtv1.SchemeGroupVersion.String() && podController.Kind == constant.KindKubevirtVMI {
-		tmpPod = pod.DeepCopy()
-		tmpPod.SetName(podController.Name)
-	} else {
-		tmpPod = pod
-	}
+		// traverse the usedIPs to find the previous allocated IPs if there be
+		// reference issue: https://github.com/spidernet-io/spiderpool/issues/2517
+		allocatedIPFromRecords, hasFound := findAllocatedIPFromRecords(allocatedRecords, nic, key, string(pod.UID))
```
Comment (weizhoublue) [inline pkg/ippoolmanager/ippool_manager.go:183]: 需要日志，可能是 error 级别的日志，说明是从 没 EP 这样一种特殊情况下获取到了 以前的 ip

Comment (Icarus9913) [reply pkg/ippoolmanager/ippool_manager.go:185]: 也不一定是没有endpoint对象，例如使用multus的注解双网卡，
第一次调用CNI都成功，第二次调用CNI分配完IP，再去更新Endpoint对象失败了。---》紧接着重新分配IP就有可能进入这里，已补充warn级别日志。

File: pkg/ipam/allocate.go [hunk 2]
```diff
@@ -356,10 +356,21 @@ func (i *ipam) allocateIPFromCandidate(ctx context.Context, c *PoolCandidate, ni
...
+					continue
+				}
+
+				// check whether the memory data is same with the IPPool resource recorded data or not
+				poolIPAllocation, ok := poolIPAllocations[*oldRes.IP.Address]
+				if ok && poolIPAllocation.PodUID == string(pod.UID) && poolIPAllocation.NIC == nic {
+					logger.Sugar().Infof("Reuse allocated IPv%d IP %s for NIC %s from IPPool %s", c.IPVersion, *oldRes.IP.Address, nic, ipPool.Name)
+					oldRes.Routes = convert.ConvertSpecRoutesToOAIRoutes(nic, ipPool.Spec.Routes)
+					oldRes.CleanGateway = cleanGateway
+					return oldRes, nil
```
Comment (weizhoublue) [inline pkg/ipam/allocate.go:372]: 如果 pool 中没数据，应该清除本地 的 数据 ？
如果 pool 中数据不一致，应该纠正本地的数据 ？
