### PR TITLE
fix: Added retries to avoid openvswitch installation failures.

### LINKED ISSUE #4170: ci: failed to install openvswitch
action url: https://github.com/spidernet-io/spiderpool/actions/runs/11334266559

### PR DESCRIPTION
**Pull request by ty-dc**
# Thanks for contributing!

**Notice**:

* [ ] unite test or E2E test
* [ ] do not forget essential code comment and log
* [ ] document for the PR
* [ ] release note label
  "release/none"
  "release/bug"
  "release/feature"
* [ ] read about  Contribution notice: <https://spidernet-io.github.io/spiderpool/latest/develop/contributing/>

**What issue(s) does this PR fix**:

Fixes #4170

**Special notes for your reviewer**:

```
=========install openvswitch
debconf: delaying package configuration, since apt-utils is not installed
A dependency job for openvswitch-switch.service failed. See 'journalctl -xe' for details.
```

### CODE REVIEW

File: test/scripts/install-ovs.sh [hunk 1]
```diff
@@ -57,14 +57,32 @@ fi
 
 echo -e "\033[35m Succeed to create vlan interface: ${HOST_ADDITIONAL_INTERFACE}.${VLAN30}、 ${HOST_ADDITIONAL_INTERFACE}.${VLAN40} in kind-node ${VLAN_GATEWAY_CONTAINER} \033[0m"
 
-KIND_NODES=`kind get nodes --name ${E2E_CLUSTER_NAME}`
-for NODE in $KIND_NODES ; do
+KIND_NODES=$(kind get nodes --name ${E2E_CLUSTER_NAME})
+for NODE in $KIND_NODES; do
   echo "=========connect node ${NODE} to additional docker network ${DOCKER_ADDITIONAL_NETWORK}"
   docker network connect ${DOCKER_ADDITIONAL_NETWORK} ${NODE}
```
Comment (weizhoublue) [inline test/scripts/install-ovs.sh:64]: set -o errexit
set -o pipefail
set -o nounset

Comment (ty-dc) [reply test/scripts/install-ovs.sh:64]: 前面有加，缺 pipefail，已补充

**Review by weizhoublue — APPROVED** [review]

**Review by cyclinder — APPROVED** [review]
