### PR TITLE
Optimize clean scripts

### LINKED ISSUE #3696: Optimize the script for cleaning up spiderpool residual resources
### Spiderpool Version

v0.9.3

### Bug Type

Installation Issue

### Main CNI

macvlan

### What happened?

Uninstall spiderpool and directly delete namespace without using helm uninstall, which results in wehbhook remaining. The cleanCRD.sh script fails to run.

### What did you expect to happen?

success

### How to reproduce it (as minimally and precisely as possible)

kubectl delete ns spiderpool-ns

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ty-dc**
#### What type of PR is this?

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #3696 

**Special notes for your reviewer**:

```
➜  spiderpool git:(fix/3696) kubectl delete ns spiderpool-ns              
namespace "spiderpool-ns" deleted
➜  spiderpool git:(fix/3696) kubectl get MutatingWebhookConfiguration -A
NAME                    WEBHOOKS   AGE
spiderpool-controller   5          76s
➜  spiderpool git:(fix/3696) bash ./tools/scripts/cleanCRD.sh
mutatingwebhookconfiguration.admissionregistration.k8s.io "spiderpool-controller" deleted
validatingwebhookconfiguration.admissionregistration.k8s.io "spiderpool-controller" deleted
spiderippool.spiderpool.spidernet.io/ippool-test patched
No resources found
spidercoordinator.spiderpool.spidernet.io/default patched
No resources found
customresourcedefinition.apiextensions.k8s.io "spiderendpoints.spiderpool.spidernet.io" deleted
customresourcedefinition.apiextensions.k8s.io "spiderippools.spiderpool.spidernet.io" deleted
customresourcedefinition.apiextensions.k8s.io "spiderreservedips.spiderpool.spidernet.io" deleted
customresourcedefinition.apiextensions.k8s.io "spidersubnets.spiderpool.spidernet.io" deleted
customresourcedefinition.apiextensions.k8s.io "spidercoordinators.spiderpool.spidernet.io" deleted
customresourcedefinition.apiextensions.k8s.io "spidermultusconfigs.spiderpool.spidernet.io" deleted
```

### CODE REVIEW

File: tools/scripts/cleanCRD.sh [hunk 1]
```diff
@@ -3,6 +3,10 @@
 # Copyright 2022 Authors of spidernet-io
 # SPDX-License-Identifier: Apache-2.0
```
Comment (weizhoublue) [inline tools/scripts/cleanCRD.sh:5]: I suggest to add `set -x` at the very beginning , for checking log and easily debugging

**Review by weizhoublue — APPROVED** [review]
