### PR TITLE
e2e: fix ipv6 address abbreviation and supplement PodCIDRType for coordinator spec

### LINKED ISSUE #2070: Night CI 2023-07-24: Failed
action url: https://github.com/spidernet-io/spiderpool/actions/runs/5649394682

### PR DESCRIPTION
**Pull request by ty-dc**
**make sure your commit is signed off**
Signed-off-by: ty-dc [tao.yang@daocloud.io](mailto:tao.yang@daocloud.io)

fix #2070  and increase PodCIDRType for coordinator

### CODE REVIEW

**Review by Icarus9913 — APPROVED** [review]

**Review by Icarus9913 — APPROVED** [review]

File: test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go [hunk 1]
```diff
@@ -354,6 +358,9 @@ var _ = Describe("MacvlanOverlayOne", Label("overlay", "one-nic", "coordinator")
 				GinkgoWriter.Printf("The v4 gateway detects an abnormal message %v \n", networkV4ErrString)
 			}
 			if frame.Info.IpV6Enabled {
+				// The ipv6 address on the network interface will be abbreviated. For example fd00:0c3d::2 becomes fd00:c3d::2.
+				// Abbreviate the expected ipv6 address and use it in subsequent assertions.
+				v6Gateway = strings.Replace(v6Gateway, ":0", ":", -1)
```
Comment (weizhoublue) [inline test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go:363]: 如果是 fd00:003d::2  其它场景呢 ？ 有没有 api 库可用么 ，而是自己 东修西补

Comment (ty-dc) [reply test/e2e/coordinator/macvlan-overlay-one/macvlan_overlay_one_test.go:363]: done

**Review by Icarus9913 — APPROVED** [review]
